#! /bin/dash

# Check if already init
if [ ! -d ".tigger" ]; then
    echo "tigger-show: error: tigger repository directory .tigger not found" 1>&2
    exit 1
fi

# Check invalid number of arguments
if [ $# -ne 1 ]; then
    echo "usage: tigger-show <commit>:<filename>" 1>&2
    exit 1
fi

if [ "$(echo "$1" | grep -Ec ':')" -ne 1 ]; then
    echo "tigger-show: error: invalid object $1" 1>&2
    exit 1
fi

current_branch=$(cat .tigger/HEAD)
commit=$(echo "$1" | cut -d ':' -f1)
fileName="$(echo "$1" | cut -d ':' -f2)"

if [ "$(echo "$commit" | wc -w)" -eq 0 ]; then
    file="$current_branch/trackCache/$fileName"
    if [ -f "$file" ]; then
        cat "$file"
        exit 0
    else
        echo "tigger-show: error: '$fileName' not found in index" 1>&2
        exit 1
    fi

# check if commit is a valid commit number and if it exists
elif [ "$(echo "$commit" | grep -Ec '^[0-9]+$')" -ne 1 ] || 
    [ ! -d "$current_branch/index/$commit" ]; then
    echo "tigger-show: error: unknown commit '$commit'" 1>&2
    exit 1
fi

# check if fileName is a valid Name
if [ "$(echo "$fileName" | grep -Ec '^[a-zA-Z0-9][a-zA-Z0-9._-]*$')" -ne 1 ]; then
    echo "tigger-show: error: invalid filename '$fileName'" 1>&2
    exit 1
fi

# check if file exists in commit
if [ ! -f "$current_branch/index/$commit/$fileName" ]; then
    echo "tigger-show: error: '$fileName' not found in commit $commit" 1>&2
    exit 1
fi

cat "$current_branch/index/$commit/$fileName"




